// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const AuthModal = ({onAuthSuccess:e,onExploreDemo:t})=>{let[n,r]=(0,_.useState)(`login`),[i,a]=(0,_.useState)(!1),[o,s]=(0,_.useState)(``),[c,l]=(0,_.useState)(``),[u,d]=(0,_.useState)(`aarav.deshmukh@coep.ac.in`),[f,p]=(0,_.useState)(`password123`),[m,h]=(0,_.useState)(`Aarav Deshmukh`),[g,v]=(0,_.useState)(`password123`),[y,b]=(0,_.useState)(`B.Tech in Computer Engineering`),[x,S]=(0,_.useState)(`COEP Technological University, Pune`),[C,w]=(0,_.useState)(`JavaScript, React, Python, SQL`),[T,E]=(0,_.useState)(`full-stack-developer`);return(0,U.jsxs)(`div`,{style:{minHeight:`100vh`,background:`radial-gradient(circle at 50% 20%, #0F4CFF22 0%, transparent 60%), #020617`,display:`flex`,flexDirection:`column`,alignItems:`center`,justifyContent:`center`,padding:`2rem 1.5rem`,position:`relative`,overflow:`hidden`},children:[(0,U.jsx)(`div`,{style:{position:`absolute`,inset:0,backgroundImage:`
          linear-gradient(to right, rgba(0, 212, 255, 0.05) 1px, transparent 1px),
          linear-gradient(to bottom, rgba(15, 76, 255, 0.05) 1px, transparent 1px)
        `,backgroundSize:`40px 40px`,pointerEvents:`none`}}),(0,U.jsx)(`div`,{style:{position:`absolute`,top:`15%`,left:`10%`,width:`320px`,height:`320px`,borderRadius:`50%`,background:`radial-gradient(circle, rgba(0, 212, 255, 0.15) 0%, transparent 70%)`,filter:`blur(50px)`,pointerEvents:`none`}}),(0,U.jsx)(`div`,{style:{position:`absolute`,bottom:`10%`,right:`10%`,width:`380px`,height:`380px`,borderRadius:`50%`,background:`radial-gradient(circle, rgba(15, 76, 255, 0.2) 0%, transparent 70%)`,filter:`blur(60px)`,pointerEvents:`none`}}),(0,U.jsxs)(`div`,{style:{textAlign:`center`,marginBottom:`2rem`,position:`relative`,zIndex:1},children:[(0,U.jsxs)(`div`,{style:{display:`inline-flex`,alignItems:`center`,gap:`0.65rem`,background:`rgba(15, 76, 255, 0.12)`,border:`1px solid rgba(0, 212, 255, 0.3)`,padding:`0.4rem 1rem`,borderRadius:`9999px`,marginBottom:`0.85rem`},children:[(0,U.jsx)(wn,{size:16,color:`#00D4FF`}),(0,U.jsx)(`span`,{style:{fontSize:`0.82rem`,fontWeight:700,color:`#00D4FF`,letterSpacing:`0.05em`},children:`SKILLTOINCOME CAREER PLATFORM`})]}),(0,U.jsxs)(`h1`,{style:{fontSize:`2.5rem`,fontWeight:800,color:`#f8fafc`,letterSpacing:`-0.03em`,textShadow:`0 0 30px rgba(0, 212, 255, 0.3)`},children:[`SKILL`,(0,U.jsx)(`span`,{style:{color:`#00D4FF`},children:`TO`}),`INCOME`]}),(0,U.jsx)(`p`,{style:{color:`#94a3b8`,fontSize:`0.95rem`,marginTop:`0.35rem`},children:`Build Skills. Discover Jobs. Grow Your Career.`})]}),(0,U.jsxs)(`div`,{style:{width:`100%`,maxWidth:n===`register`?`580px`:`460px`,background:`rgba(15, 23, 42, 0.75)`,backdropFilter:`blur(20px)`,border:`1px solid rgba(0, 212, 255, 0.25)`,boxShadow:`0 20px 50px rgba(2, 6, 23, 0.8), 0 0 25px rgba(15, 76, 255, 0.2)`,borderRadius:`16px`,padding:`2.25rem`,position:`relative`,zIndex:1,transition:`all 0.3s ease`},children:[o&&(0,U.jsxs)(`div`,{style:{background:`rgba(244, 63, 94, 0.15)`,border:`1px solid rgba(244, 63, 94, 0.4)`,borderRadius:`8px`,padding:`0.75rem 1rem`,color:`#fb7185`,fontSize:`0.84rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`1.25rem`},children:[(0,U.jsx)(Ae,{size:16}),(0,U.jsx)(`span`,{children:o})]}),c&&(0,U.jsxs)(`div`,{style:{background:`rgba(16, 185, 129, 0.15)`,border:`1px solid rgba(16, 185, 129, 0.4)`,borderRadius:`8px`,padding:`0.75rem 1rem`,color:`#34d399`,fontSize:`0.84rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`1.25rem`},children:[(0,U.jsx)(H,{size:16}),(0,U.jsx)(`span`,{children:c})]}),n===`login`&&(0,U.jsxs)(`form`,{onSubmit:async t=>{t.preventDefault(),s(``),a(!0);try{if(!u||!f)throw Error(`Please enter both email and password.`);e(await ap.login(u,f))}catch(e){s(e.message||`Login failed. Please check your credentials.`)}finally{a(!1)}},style:{display:`flex`,flexDirection:`column`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.4rem`,fontWeight:600},children:`Email Address`}),(0,U.jsxs)(`div`,{style:{position:`relative`},children:[(0,U.jsx)(Lt,{size:16,color:`#94a3b8`,style:{position:`absolute`,left:`12px`,top:`12px`}}),(0,U.jsx)(`input`,{type:`email`,required:!0,placeholder:`student@university.edu`,value:u,onChange:e=>d(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem 0.65rem 2.4rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.9rem`}})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`label`,{style:{fontSize:`0.82rem`,color:`#cbd5e1`,fontWeight:600},children:`Password`}),(0,U.jsx)(`button`,{type:`button`,onClick:()=>r(`forgot`),style:{background:`none`,border:`none`,color:`#00D4FF`,fontSize:`0.78rem`,cursor:`pointer`},children:`Forgot Password?`})]}),(0,U.jsxs)(`div`,{style:{position:`relative`},children:[(0,U.jsx)(jt,{size:16,color:`#94a3b8`,style:{position:`absolute`,left:`12px`,top:`12px`}}),(0,U.jsx)(`input`,{type:`password`,required:!0,placeholder:`••••••••`,value:f,onChange:e=>p(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem 0.65rem 2.4rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.9rem`}})]})]}),(0,U.jsxs)(`button`,{type:`submit`,disabled:i,className:`btn-primary`,style:{width:`100%`,padding:`0.8rem`,fontSize:`0.95rem`,justifyContent:`center`,background:`linear-gradient(135deg, #0F4CFF, #00D4FF)`},children:[(0,U.jsx)(`span`,{children:i?`Signing in...`:`Sign In to Career Platform`}),(0,U.jsx)(ne,{size:16})]}),(0,U.jsxs)(`div`,{style:{position:`relative`,textAlign:`center`,margin:`0.5rem 0`},children:[(0,U.jsx)(`div`,{style:{position:`absolute`,top:`50%`,left:0,right:0,height:`1px`,background:`rgba(255, 255, 255, 0.1)`}}),(0,U.jsx)(`span`,{style:{position:`relative`,background:`#0b1329`,padding:`0 0.75rem`,fontSize:`0.75rem`,color:`#64748b`},children:`OR SECURE SINGLE SIGN-ON`})]}),(0,U.jsxs)(`button`,{type:`button`,onClick:async()=>{s(``),a(!0);try{e(await ap.loginWithGoogle())}catch(e){s(e.message||`Google authentication failed.`)}finally{a(!1)}},disabled:i,className:`btn-secondary`,style:{width:`100%`,padding:`0.75rem`,justifyContent:`center`,fontSize:`0.88rem`},children:[(0,U.jsxs)(`svg`,{width:`18`,height:`18`,viewBox:`0 0 24 24`,style:{marginRight:`6px`},children:[(0,U.jsx)(`path`,{fill:`#4285F4`,d:`M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z`}),(0,U.jsx)(`path`,{fill:`#34A853`,d:`M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z`}),(0,U.jsx)(`path`,{fill:`#FBBC05`,d:`M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.06H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.94l2.85-2.22.81-.63z`}),(0,U.jsx)(`path`,{fill:`#EA4335`,d:`M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.06l3.66 2.84c.87-2.6 3.3-4.52 6.16-4.52z`})]}),(0,U.jsx)(`span`,{children:`Continue with Google`})]}),(0,U.jsxs)(`div`,{style:{textAlign:`center`,fontSize:`0.84rem`,color:`#94a3b8`,marginTop:`0.5rem`},children:[`Don't have an account?`,` `,(0,U.jsx)(`button`,{type:`button`,onClick:()=>r(`register`),style:{background:`none`,border:`none`,color:`#00D4FF`,fontWeight:600,cursor:`pointer`},children:`Create Account`})]})]}),n===`register`&&(0,U.jsxs)(`form`,{onSubmit:async t=>{t.preventDefault(),s(``),a(!0);try{if(f!==g)throw Error(`Passwords do not match.`);if(f.length<6)throw Error(`Password must be at least 6 characters.`);let t=C.split(`,`).map(e=>e.trim().toLowerCase()).filter(Boolean);e(await ap.register({fullName:m,email:u,password:f,education:y,college:x,skills:t,targetRole:T}))}catch(e){s(e.message||`Registration failed.`)}finally{a(!1)}},style:{display:`flex`,flexDirection:`column`,gap:`1.1rem`},children:[(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`1fr 1fr`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Full Name *`}),(0,U.jsxs)(`div`,{style:{position:`relative`},children:[(0,U.jsx)(Wn,{size:15,color:`#94a3b8`,style:{position:`absolute`,left:`10px`,top:`11px`}}),(0,U.jsx)(`input`,{type:`text`,required:!0,value:m,onChange:e=>h(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem 0.6rem 2.2rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Email Address *`}),(0,U.jsxs)(`div`,{style:{position:`relative`},children:[(0,U.jsx)(Lt,{size:15,color:`#94a3b8`,style:{position:`absolute`,left:`10px`,top:`11px`}}),(0,U.jsx)(`input`,{type:`email`,required:!0,value:u,onChange:e=>d(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem 0.6rem 2.2rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]})]})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`1fr 1fr`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Password *`}),(0,U.jsx)(`input`,{type:`password`,required:!0,placeholder:`Min. 6 chars`,value:f,onChange:e=>p(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Confirm Password *`}),(0,U.jsx)(`input`,{type:`password`,required:!0,value:g,onChange:e=>v(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`1fr 1fr`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Education / Degree`}),(0,U.jsx)(`input`,{type:`text`,value:y,onChange:e=>b(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`College / Institute`}),(0,U.jsx)(`input`,{type:`text`,value:x,onChange:e=>S(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Verified Skills (comma separated)`}),(0,U.jsx)(`input`,{type:`text`,value:C,onChange:e=>w(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Target Job Role`}),(0,U.jsxs)(`select`,{value:T,onChange:e=>E(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.85rem`},children:[(0,U.jsx)(`option`,{value:`full-stack-developer`,children:`Full Stack Developer`}),(0,U.jsx)(`option`,{value:`ai-ml-engineer`,children:`AI / Machine Learning Engineer`}),(0,U.jsx)(`option`,{value:`data-analyst`,children:`Data Analyst & BI`}),(0,U.jsx)(`option`,{value:`cloud-engineer`,children:`Cloud & DevOps Engineer`}),(0,U.jsx)(`option`,{value:`cybersecurity-analyst`,children:`Cybersecurity Analyst`})]})]}),(0,U.jsxs)(`button`,{type:`submit`,disabled:i,className:`btn-primary`,style:{width:`100%`,padding:`0.8rem`,fontSize:`0.95rem`,justifyContent:`center`,background:`linear-gradient(135deg, #0F4CFF, #00D4FF)`,marginTop:`0.5rem`},children:[(0,U.jsx)(`span`,{children:i?`Creating Profile...`:`Complete Registration`}),(0,U.jsx)(ne,{size:16})]}),(0,U.jsxs)(`div`,{style:{textAlign:`center`,fontSize:`0.84rem`,color:`#94a3b8`},children:[`Already registered?`,` `,(0,U.jsx)(`button`,{type:`button`,onClick:()=>r(`login`),style:{background:`none`,border:`none`,color:`#00D4FF`,fontWeight:600,cursor:`pointer`},children:`Sign In`})]})]}),n===`forgot`&&(0,U.jsxs)(`form`,{onSubmit:async e=>{e.preventDefault(),s(``),a(!0);try{if(!u)throw Error(`Please enter your registered email address.`);await ap.resetPassword(u),l(`Password reset instructions sent to your email.`),setTimeout(()=>{l(``),r(`login`)},3e3)}catch(e){s(e.message||`Failed to send reset link.`)}finally{a(!1)}},style:{display:`flex`,flexDirection:`column`,gap:`1.25rem`},children:[(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.86rem`,lineHeight:`1.4`},children:`Enter your registered email address and we'll send you instructions to reset your password.`}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.4rem`,fontWeight:600},children:`Email Address`}),(0,U.jsx)(`input`,{type:`email`,required:!0,value:u,onChange:e=>d(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(2, 6, 23, 0.7)`,border:`1px solid rgba(0, 212, 255, 0.2)`,color:`#f8fafc`,fontSize:`0.9rem`}})]}),(0,U.jsx)(`button`,{type:`submit`,disabled:i,className:`btn-primary`,style:{width:`100%`,padding:`0.75rem`,justifyContent:`center`},children:(0,U.jsx)(`span`,{children:i?`Sending...`:`Send Password Reset Link`})}),(0,U.jsx)(`div`,{style:{textAlign:`center`},children:(0,U.jsx)(`button`,{type:`button`,onClick:()=>r(`login`),style:{background:`none`,border:`none`,color:`#94a3b8`,fontSize:`0.82rem`,cursor:`pointer`},children:`← Back to Login`})})]}),(0,U.jsx)(`div`,{style:{marginTop:`1.5rem`,paddingTop:`1rem`,borderTop:`1px solid rgba(255, 255, 255, 0.08)`,textAlign:`center`},children:(0,U.jsxs)(`button`,{type:`button`,onClick:t,style:{background:`none`,border:`none`,color:`#38bdf8`,fontSize:`0.82rem`,cursor:`pointer`,display:`inline-flex`,alignItems:`center`,gap:`0.4rem`},children:[(0,U.jsx)(`span`,{children:`Skip Login & Explore 3D Home (Judge / Demo Mode)`}),(0,U.jsx)(ne,{size:13})]})})]})]})};
