// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const CareerSyncMonitorView = ({onNavigateTab:e})=>{let[t,n]=(0,_.useState)(null),[r,i]=(0,_.useState)(!0),[a,o]=(0,_.useState)(!1),[s,c]=(0,_.useState)(``);(0,_.useEffect)(()=>{l()},[]);let l=async()=>{i(!0);try{let e=await W.getJobSyncStatus();n(e)}catch(e){console.error(e)}finally{i(!1)}},u=async()=>{o(!0),c(``);try{let e=await W.triggerJobSync();e?.status&&n(e.status),c(e.message||`Job synchronization completed successfully.`),setTimeout(()=>c(``),5e3)}catch(e){alert(e.message||`Error triggering sync`)}finally{o(!1)}},d=e=>{if(!e)return`Never`;try{let t=Math.floor((Date.now()-new Date(e).getTime())/1e3);return t<60?`Just now`:t<3600?`${Math.floor(t/60)} mins ago`:t<86400?`${Math.floor(t/3600)} hours ago`:`${Math.floor(t/86400)} days ago`}catch{return e}};return(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`2rem`,maxWidth:`1050px`,margin:`0 auto`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`2rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{background:`rgba(16, 185, 129, 0.15)`,color:`#34d399`,padding:`0.2rem 0.65rem`,borderRadius:`6px`,fontSize:`0.75rem`,fontWeight:700},children:`Module 9 & 24 • Admin & System Monitoring`}),(0,U.jsx)(`span`,{style:{color:`#94a3b8`,fontSize:`0.82rem`},children:`Continuous Job Sync Engine`})]}),(0,U.jsx)(`h1`,{style:{fontSize:`1.9rem`,color:`#f8fafc`,fontWeight:800},children:`Live Job Ingestion & Feed Monitor`}),(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.92rem`,marginTop:`0.35rem`},children:`Monitor external authorized job APIs, rate limit quotas, normalized data ingestion, and duplicate detection runs.`})]}),(0,U.jsx)(`div`,{style:{display:`flex`,gap:`0.75rem`},children:(0,U.jsxs)(`button`,{onClick:u,disabled:a,className:`btn-primary`,children:[(0,U.jsx)(on,{size:16,className:a?`spin`:``}),(0,U.jsx)(`span`,{children:a?`Ingesting Feeds...`:`Trigger Sync Now`})]})})]}),s&&(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`,padding:`0.85rem 1rem`,background:`rgba(16, 185, 129, 0.15)`,border:`1px solid rgba(16, 185, 129, 0.35)`,borderRadius:`8px`,color:`#34d399`,fontSize:`0.86rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`,fontWeight:600},children:[(0,U.jsx)(H,{size:18}),(0,U.jsx)(`span`,{children:s})]})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(200px, 1fr))`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#38bdf8`,marginBottom:`0.4rem`},children:[(0,U.jsx)(ze,{size:16}),(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,fontWeight:700,textTransform:`uppercase`},children:`Last Successful Sync`})]}),(0,U.jsx)(`div`,{style:{fontSize:`1.25rem`,fontWeight:800,color:`#f8fafc`},children:d(t?.last_successful_sync)}),(0,U.jsx)(`div`,{style:{fontSize:`0.72rem`,color:`#64748b`,marginTop:`0.2rem`},children:t?.last_successful_sync||`Synchronized`})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#34d399`,marginBottom:`0.4rem`},children:[(0,U.jsx)(qe,{size:16}),(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,fontWeight:700,textTransform:`uppercase`},children:`Active Jobs In Store`})]}),(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#f8fafc`},children:t?.total_jobs_in_db||6}),(0,U.jsx)(`div`,{style:{fontSize:`0.72rem`,color:`#64748b`,marginTop:`0.2rem`},children:`Duplicate-free normalized records`})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#a78bfa`,marginBottom:`0.4rem`},children:[(0,U.jsx)(P,{size:16}),(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,fontWeight:700,textTransform:`uppercase`},children:`Last Jobs Ingested`})]}),(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#f8fafc`},children:t?.last_jobs_fetched||6}),(0,U.jsx)(`div`,{style:{fontSize:`0.72rem`,color:`#64748b`,marginTop:`0.2rem`},children:`Across 3 authorized public feeds`})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#fbbf24`,marginBottom:`0.4rem`},children:[(0,U.jsx)(gn,{size:16}),(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,fontWeight:700,textTransform:`uppercase`},children:`Scheduled Interval`})]}),(0,U.jsxs)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#f8fafc`},children:[t?.sync_interval_minutes||60,`m`]}),(0,U.jsx)(`div`,{style:{fontSize:`0.72rem`,color:`#64748b`,marginTop:`0.2rem`},children:`Firebase scheduled continuous cycle`})]})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,marginBottom:`1.25rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(gn,{size:18,color:`#38bdf8`}),(0,U.jsx)(`span`,{children:`Connected Job Sources & Authorization Status`})]}),(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:(t?.sources||[]).map((e,t)=>(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.6)`,border:`1px solid var(--border-subtle)`,borderRadius:`8px`,padding:`1rem`,display:`flex`,justifyContent:`space-between`,alignItems:`center`,flexWrap:`wrap`,gap:`0.75rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`div`,{style:{fontSize:`0.92rem`,fontWeight:600,color:`#f8fafc`},children:e.name}),(0,U.jsxs)(`div`,{style:{fontSize:`0.76rem`,color:`#94a3b8`,marginTop:`0.2rem`},children:[`Last health ping: `,d(e.last_ping)]})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`1.5rem`},children:[(0,U.jsxs)(`div`,{style:{textAlign:`right`},children:[(0,U.jsx)(`div`,{style:{fontSize:`0.74rem`,color:`#94a3b8`},children:`API Rate Quota`}),(0,U.jsx)(`div`,{style:{fontSize:`0.82rem`,fontWeight:600,color:`#38bdf8`},children:e.quota_used})]}),(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,fontWeight:700,padding:`0.25rem 0.65rem`,borderRadius:`9999px`,background:`rgba(16, 185, 129, 0.15)`,color:`#34d399`,border:`1px solid rgba(16, 185, 129, 0.3)`},children:e.status})]})]},t))})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,marginBottom:`1rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(bn,{size:18,color:`#10b981`}),(0,U.jsx)(`span`,{children:`Compliance & Ethics Audit Log`})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.65rem`,fontSize:`0.84rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#cbd5e1`},children:[(0,U.jsx)(H,{size:16,color:`#10b981`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`LinkedIn Policy:`}),` 100% compliant — Zero scraping of private or login-gated pages.`]})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#cbd5e1`},children:[(0,U.jsx)(H,{size:16,color:`#10b981`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`Robots.txt & Rate Limiting:`}),` Respects all publisher crawl directives and hourly query caps.`]})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#cbd5e1`},children:[(0,U.jsx)(H,{size:16,color:`#10b981`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`Duplicate Filtering:`}),` Ingestion pipeline hashes (company + title + sourceJobId) to discard duplicates.`]})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,color:`#cbd5e1`},children:[(0,U.jsx)(H,{size:16,color:`#10b981`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`Source Attribution:`}),` Every job listing transparently credits original source and provides direct links.`]})]})]})]})]})};
