// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const CareerResumeCustomizerView = ({onNavigateTab:e})=>{let[t,n]=(0,_.useState)([]),[r,i]=(0,_.useState)(``),[a,o]=(0,_.useState)(`Aarav Deshmukh - Aspiring Full Stack Engineer
Education: B.Tech in Computer Engineering, COEP Technological University, Pune (2027)
Technical Skills: JavaScript, React, HTML5, CSS3, SQL, Python, Git
Projects: E-Governance Citizen Service Portal built with React and Node.js with PostgreSQL backend.
Experience: 1 year of academic coursework and full-stack web internships.`),[s,c]=(0,_.useState)(!1),[l,u]=(0,_.useState)(null);(0,_.useEffect)(()=>{d()},[]);let d=async()=>{try{let e=await W.getJobs();n(e||[]),e&&e.length>0&&i(e[0].id)}catch(e){console.error(e)}},f=e=>{e.preventDefault();let n=t.find(e=>e.id===r);n&&(c(!0),setTimeout(()=>{let e=a.toLowerCase(),t=n.skills||[`react`,`node.js`,`sql`,`javascript`],r=t.filter(t=>e.includes(t.toLowerCase())),i=t.filter(t=>!e.includes(t.toLowerCase()));e.includes(`project`)||e.includes(`portal`)||e.includes(`built`);let o=/\d+%|\d+\s*(users|requests|ms)/.test(e);u({jobTitle:n.title,company:n.company,matchingSkills:r,missingSkills:i,relevanceScore:Math.round(r.length/(t.length||1)*100),skillsToEmphasize:r,projectsToEmphasize:[`Highlight your E-Governance Portal architecture, focusing on component structure and API endpoints.`,`Emphasize database schema design and queries implemented with PostgreSQL/SQL.`],missingKeywords:i,improvementNotes:[i.length>0?`Your resume currently lacks mention of: ${i.join(`, `)}. If you have practical experience with these, add them to your technical skills section.`:`Strong skill coverage for this opening.`,o?`Good use of quantifiable metrics in project bullets.`:`Add measurable outcomes (e.g. latency reduced, user counts, scale handled) to boost recruiter impact.`,`Never keyword-stuff or fabricate qualifications you have not worked on.`]}),c(!1)},400))},p=t.find(e=>e.id===r);return(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`2rem`,maxWidth:`1050px`,margin:`0 auto`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`2rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{background:`rgba(168, 85, 247, 0.15)`,color:`#c084fc`,padding:`0.2rem 0.65rem`,borderRadius:`6px`,fontSize:`0.75rem`,fontWeight:700},children:`Module 7 • /career/resume`}),(0,U.jsx)(`span`,{style:{color:`#94a3b8`,fontSize:`0.82rem`},children:`Job-Specific Alignment Engine`})]}),(0,U.jsx)(`h1`,{style:{fontSize:`1.9rem`,color:`#f8fafc`,fontWeight:800},children:`Job-Specific Resume Customizer`}),(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.92rem`,marginTop:`0.35rem`},children:`Compare your resume against a specific target job opening to pinpoint missing keywords, emphasize relevant projects, and ensure ATS readability without falsification.`})]}),(0,U.jsx)(`button`,{onClick:()=>e(`career_jobs`),className:`btn-secondary`,children:(0,U.jsx)(`span`,{children:`← Discover More Jobs`})})]}),(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`,padding:`0.85rem 1rem`,background:`rgba(15, 23, 42, 0.6)`,border:`1px solid rgba(168, 85, 247, 0.3)`,borderRadius:`8px`,display:`flex`,alignItems:`center`,gap:`0.75rem`,fontSize:`0.82rem`,color:`#e9d5ff`},children:[(0,U.jsx)(bn,{size:18,color:`#a855f7`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`Ethical AI Guardrail:`}),` SkillBridge helps you strategically emphasize your authentic capabilities. It never generates keyword-stuffed text or fabricates skills, certifications, or experience.`]})]})]}),(0,U.jsxs)(`form`,{onSubmit:f,style:{display:`flex`,flexDirection:`column`,gap:`1.5rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`label`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,fontSize:`0.92rem`,color:`#f8fafc`,fontWeight:600,marginBottom:`0.5rem`},children:[(0,U.jsx)(ve,{size:17,color:`#38bdf8`}),(0,U.jsx)(`span`,{children:`Select Target Job Opening for Comparison`})]}),(0,U.jsx)(`select`,{value:r,onChange:e=>i(e.target.value),style:{width:`100%`,padding:`0.75rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.8)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`},children:t.map(e=>(0,U.jsxs)(`option`,{value:e.id,children:[e.title,` — `,e.company,` (`,e.location,`) [`,e.source,`]`]},e.id))}),p&&(0,U.jsxs)(`div`,{style:{marginTop:`0.75rem`,padding:`0.75rem`,background:`rgba(15, 23, 42, 0.5)`,borderRadius:`6px`,fontSize:`0.82rem`,color:`#cbd5e1`},children:[(0,U.jsx)(`strong`,{children:`Required Stack: `}),(0,U.jsx)(`span`,{children:(p.skills||[]).join(`, `)})]})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,marginBottom:`0.5rem`},children:[(0,U.jsxs)(`label`,{style:{fontSize:`0.92rem`,color:`#f8fafc`,fontWeight:600,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(rt,{size:17,color:`#a855f7`}),(0,U.jsx)(`span`,{children:`Resume Content (Paste or Pre-loaded from Profile)`})]}),(0,U.jsx)(`span`,{style:{fontSize:`0.76rem`,color:`#94a3b8`},children:`Loaded from Career Profile`})]}),(0,U.jsx)(`textarea`,{rows:8,value:a,onChange:e=>o(e.target.value),placeholder:`Paste your resume text here...`,style:{width:`100%`,padding:`0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.8)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`,fontFamily:`inherit`,lineHeight:`1.5`}}),(0,U.jsx)(`div`,{style:{display:`flex`,justifyContent:`flex-end`,marginTop:`1rem`},children:(0,U.jsxs)(`button`,{type:`submit`,disabled:s,className:`btn-primary`,style:{padding:`0.75rem 2rem`},children:[(0,U.jsx)(wn,{size:17}),(0,U.jsx)(`span`,{children:s?`Customizing...`:`Compare Resume vs Target Job`})]})})]})]}),l&&(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`1.5rem`},children:[(0,U.jsx)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`span`,{style:{fontSize:`0.75rem`,textTransform:`uppercase`,color:`#94a3b8`,fontWeight:700},children:`Role Alignment Score`}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`baseline`,gap:`0.75rem`,marginTop:`0.2rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`2.5rem`,fontWeight:900,color:l.relevanceScore>=70?`#34d399`:`#fbbf24`},children:[l.relevanceScore,`%`]}),(0,U.jsxs)(`span`,{style:{fontSize:`0.9rem`,color:`#cbd5e1`},children:[`for `,l.jobTitle,` at `,l.company]})]})]}),(0,U.jsx)(`div`,{style:{flex:`1 1 300px`,maxWidth:`400px`},children:(0,U.jsx)(`div`,{style:{height:`8px`,background:`rgba(255, 255, 255, 0.1)`,borderRadius:`9999px`,overflow:`hidden`},children:(0,U.jsx)(`div`,{style:{width:`${l.relevanceScore}%`,height:`100%`,background:l.relevanceScore>=70?`linear-gradient(90deg, #10b981, #06b6d4)`:`linear-gradient(90deg, #f59e0b, #6366f1)`}})})})]})}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(320px, 1fr))`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.5rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.05rem`,color:`#f8fafc`,marginBottom:`0.75rem`,display:`flex`,alignItems:`center`,gap:`0.4rem`},children:[(0,U.jsx)(H,{size:17,color:`#10b981`}),(0,U.jsx)(`span`,{children:`Matching Skills & Technologies`})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.78rem`,color:`#94a3b8`,marginBottom:`0.75rem`},children:`Found in both your resume and this job requirement.`}),(0,U.jsx)(`div`,{style:{display:`flex`,flexWrap:`wrap`,gap:`0.4rem`},children:l.matchingSkills.map((e,t)=>(0,U.jsx)(`span`,{style:{background:`rgba(16, 185, 129, 0.15)`,color:`#6ee7b7`,border:`1px solid rgba(16, 185, 129, 0.3)`,padding:`0.25rem 0.65rem`,borderRadius:`4px`,fontSize:`0.8rem`,fontWeight:600},children:e},t))})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.5rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.05rem`,color:`#f8fafc`,marginBottom:`0.75rem`,display:`flex`,alignItems:`center`,gap:`0.4rem`},children:[(0,U.jsx)(In,{size:17,color:`#fbbf24`}),(0,U.jsx)(`span`,{children:`Missing Job Keywords`})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.78rem`,color:`#94a3b8`,marginBottom:`0.75rem`},children:`Required in the job posting but not detected in your current resume text.`}),(0,U.jsx)(`div`,{style:{display:`flex`,flexWrap:`wrap`,gap:`0.4rem`},children:l.missingKeywords.length===0?(0,U.jsx)(`span`,{style:{color:`#34d399`,fontSize:`0.84rem`},children:`All core job skills covered!`}):l.missingKeywords.map((e,t)=>(0,U.jsx)(`span`,{style:{background:`rgba(245, 158, 11, 0.15)`,color:`#fcd34d`,border:`1px solid rgba(245, 158, 11, 0.3)`,padding:`0.25rem 0.65rem`,borderRadius:`4px`,fontSize:`0.8rem`,fontWeight:600},children:e},t))})]})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,marginBottom:`1rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(Ct,{size:18,color:`#818cf8`}),(0,U.jsx)(`span`,{children:`Section-by-Section Customization Plan`})]}),(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:l.improvementNotes.map((e,t)=>(0,U.jsx)(`div`,{style:{padding:`0.75rem 1rem`,background:`rgba(15, 23, 42, 0.6)`,borderLeft:`3px solid #818cf8`,borderRadius:`0 8px 8px 0`,fontSize:`0.84rem`,color:`#e2e8f0`},children:e},t))})]})]})]})};
