// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const CareerApplicationsView = ({onNavigateTab:e})=>{let[t,n]=(0,_.useState)([]),[r,i]=(0,_.useState)(!0),[a,o]=(0,_.useState)(`kanban`),[s,c]=(0,_.useState)(!1),[l,u]=(0,_.useState)(null),[d,f]=(0,_.useState)(``),[p,m]=(0,_.useState)(``),[h,g]=(0,_.useState)(``),[v,y]=(0,_.useState)(`Applied`),[b,x]=(0,_.useState)(``),[S,C]=(0,_.useState)(``),[w,T]=(0,_.useState)(``),[E,D]=(0,_.useState)(`National Career Service (NCS India)`);(0,_.useEffect)(()=>{O()},[]);let O=async()=>{i(!0);try{let e=await W.getApplications();n(e||[])}catch(e){console.error(e)}finally{i(!1)}},k=()=>{u(null),f(``),m(``),g(``),y(`Preparing`),x(``),C(``),T(``),D(`Direct / External`),c(!0)},A=e=>{u(e),f(e.company||``),m(e.jobTitle||``),g(e.applicationUrl||``),y(e.status||`Saved`),x(e.notes||``),C(e.nextAction||``),T(e.nextActionDate||``),D(e.source||`Direct`),c(!0)},j=async e=>{e.preventDefault();try{l?await W.updateApplication(l.id,{status:v,notes:b,nextAction:S,nextActionDate:w}):await W.createApplication({jobId:`custom-${Date.now()}`,company:d,jobTitle:p,applicationUrl:h,status:v,notes:b,nextAction:S,nextActionDate:w,source:E}),c(!1),O()}catch(e){alert(e.message||`Error saving application`)}},M=async e=>{if(confirm(`Are you sure you want to remove this tracked application?`))try{await W.deleteApplication(e),O()}catch(e){alert(e.message||`Error deleting application`)}},N=async(e,t)=>{try{await W.updateApplication(e,{status:t}),O()}catch(e){alert(e.message||`Error updating status`)}},P=t.filter(e=>[`Applied`,`Assessment`,`Interview`].includes(e.status)),F=t.filter(e=>e.status===`Interview`).length,ee=t.filter(e=>e.nextAction&&e.nextActionDate),te=t.filter(e=>e.status===`Saved`).length;return(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`2rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`2rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{background:`rgba(99, 102, 241, 0.15)`,color:`#818cf8`,padding:`0.2rem 0.65rem`,borderRadius:`6px`,fontSize:`0.75rem`,fontWeight:700},children:`Module 8 • /applications`}),(0,U.jsx)(`span`,{style:{color:`#94a3b8`,fontSize:`0.82rem`},children:`Lifecycle Pipeline`})]}),(0,U.jsx)(`h1`,{style:{fontSize:`1.9rem`,color:`#f8fafc`,fontWeight:800},children:`Career Application Tracker`}),(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.92rem`,marginTop:`0.35rem`},children:`Track applications across 8 pipeline stages from Saved and Preparing to Interviews and Offers.`})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,gap:`0.75rem`,alignItems:`center`},children:[(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.7)`,padding:`0.25rem`,borderRadius:`8px`,border:`1px solid var(--border-subtle)`,display:`flex`},children:[(0,U.jsxs)(`button`,{onClick:()=>o(`kanban`),style:{background:a===`kanban`?`rgba(99, 102, 241, 0.25)`:`none`,color:a===`kanban`?`#38bdf8`:`#94a3b8`,border:`none`,padding:`0.4rem 0.65rem`,borderRadius:`6px`,cursor:`pointer`,display:`flex`,alignItems:`center`,gap:`0.35rem`,fontSize:`0.8rem`,fontWeight:600},children:[(0,U.jsx)(xt,{size:14}),(0,U.jsx)(`span`,{children:`Kanban`})]}),(0,U.jsxs)(`button`,{onClick:()=>o(`table`),style:{background:a===`table`?`rgba(99, 102, 241, 0.25)`:`none`,color:a===`table`?`#38bdf8`:`#94a3b8`,border:`none`,padding:`0.4rem 0.65rem`,borderRadius:`6px`,cursor:`pointer`,display:`flex`,alignItems:`center`,gap:`0.35rem`,fontSize:`0.8rem`,fontWeight:600},children:[(0,U.jsx)(On,{size:14}),(0,U.jsx)(`span`,{children:`Table`})]})]}),(0,U.jsxs)(`button`,{onClick:k,className:`btn-primary`,children:[(0,U.jsx)(tn,{size:16}),(0,U.jsx)(`span`,{children:`Track Application`})]})]})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(170px, 1fr))`,gap:`1rem`,marginTop:`1.5rem`},children:[(0,U.jsxs)(`div`,{style:{background:`rgba(30, 41, 59, 0.6)`,padding:`1rem`,borderRadius:`10px`,border:`1px solid var(--border-subtle)`},children:[(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#f8fafc`},children:t.length}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#94a3b8`},children:`Total Applications`})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(56, 189, 248, 0.1)`,padding:`1rem`,borderRadius:`10px`,border:`1px solid rgba(56, 189, 248, 0.2)`},children:[(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#38bdf8`},children:P.length}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#38bdf8`},children:`In Active Pipeline`})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(168, 85, 247, 0.1)`,padding:`1rem`,borderRadius:`10px`,border:`1px solid rgba(168, 85, 247, 0.2)`},children:[(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#c084fc`},children:F}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#c084fc`},children:`Interviews Scheduled`})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(245, 158, 11, 0.1)`,padding:`1rem`,borderRadius:`10px`,border:`1px solid rgba(245, 158, 11, 0.2)`},children:[(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#fbbf24`},children:ee.length}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#fbbf24`},children:`Pending Actions`})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(148, 163, 184, 0.1)`,padding:`1rem`,borderRadius:`10px`,border:`1px solid var(--border-subtle)`},children:[(0,U.jsx)(`div`,{style:{fontSize:`1.5rem`,fontWeight:800,color:`#94a3b8`},children:te}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#94a3b8`},children:`Saved Openings`})]})]})]}),r?(0,U.jsx)(`div`,{style:{textAlign:`center`,padding:`3rem`,color:`#94a3b8`},children:`Loading application pipeline...`}):a===`kanban`?(0,U.jsx)(`div`,{style:{display:`flex`,gap:`1rem`,overflowX:`auto`,paddingBottom:`1rem`,minHeight:`480px`},children:Dr.map(e=>{let n=t.filter(t=>t.status===e.id);return(0,U.jsxs)(`div`,{style:{flex:`0 0 260px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,borderRadius:`12px`,padding:`1rem`,display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,paddingBottom:`0.5rem`,borderBottom:`1px solid var(--border-subtle)`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{width:`8px`,height:`8px`,borderRadius:`50%`,background:e.color}}),(0,U.jsx)(`span`,{style:{fontSize:`0.85rem`,fontWeight:700,color:`#f8fafc`},children:e.label})]}),(0,U.jsx)(`span`,{style:{fontSize:`0.72rem`,color:`#94a3b8`,background:`rgba(30, 41, 59, 0.8)`,padding:`0.1rem 0.45rem`,borderRadius:`9999px`},children:n.length})]}),(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`,overflowY:`auto`},children:n.length===0?(0,U.jsx)(`div`,{style:{textAlign:`center`,padding:`1.5rem 0.5rem`,fontSize:`0.75rem`,color:`#64748b`},children:`No applications`}):n.map(e=>(0,U.jsxs)(`div`,{className:`glass-card`,style:{padding:`0.85rem`,display:`flex`,flexDirection:`column`,gap:`0.5rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`},children:[(0,U.jsx)(`span`,{style:{fontSize:`0.7rem`,color:`#94a3b8`,textTransform:`uppercase`},children:e.source||`Direct`}),(0,U.jsxs)(`div`,{style:{display:`flex`,gap:`0.3rem`},children:[(0,U.jsx)(`button`,{onClick:()=>A(e),style:{background:`none`,border:`none`,color:`#94a3b8`,cursor:`pointer`,padding:`2px`},title:`Edit notes & action`,children:(0,U.jsx)(Zt,{size:13})}),(0,U.jsx)(`button`,{onClick:()=>M(e.id),style:{background:`none`,border:`none`,color:`#f43f5e`,cursor:`pointer`,padding:`2px`},title:`Delete`,children:(0,U.jsx)(Mn,{size:13})})]})]}),(0,U.jsx)(`div`,{style:{fontWeight:600,color:`#f8fafc`,fontSize:`0.9rem`},children:e.jobTitle}),(0,U.jsx)(`div`,{style:{fontSize:`0.78rem`,color:`#38bdf8`},children:e.company}),e.nextAction&&(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.7)`,padding:`0.4rem`,borderRadius:`4px`,fontSize:`0.74rem`},children:[(0,U.jsx)(`span`,{style:{color:`#fbbf24`,fontWeight:600},children:`Action: `}),(0,U.jsx)(`span`,{style:{color:`#cbd5e1`},children:e.nextAction}),e.nextActionDate&&(0,U.jsxs)(`div`,{style:{color:`#94a3b8`,fontSize:`0.7rem`,marginTop:`0.15rem`},children:[`Due: `,e.nextActionDate]})]}),(0,U.jsxs)(`div`,{style:{paddingTop:`0.4rem`,borderTop:`1px solid var(--border-subtle)`,display:`flex`,justifyContent:`space-between`,alignItems:`center`},children:[(0,U.jsx)(`select`,{value:e.status,onChange:t=>N(e.id,t.target.value),style:{background:`rgba(15, 23, 42, 0.8)`,border:`1px solid var(--border-subtle)`,color:`#cbd5e1`,fontSize:`0.72rem`,padding:`0.2rem 0.4rem`,borderRadius:`4px`},children:Dr.map(e=>(0,U.jsx)(`option`,{value:e.id,children:e.label},e.id))}),e.applicationUrl&&(0,U.jsx)(`a`,{href:e.applicationUrl,target:`_blank`,rel:`noreferrer`,style:{color:`#38bdf8`,fontSize:`0.72rem`,display:`flex`,alignItems:`center`,gap:`0.2rem`},children:(0,U.jsx)($e,{size:12})})]})]},e.id))})]},e.id)})}):(0,U.jsx)(`div`,{className:`glass-panel`,style:{padding:`1.5rem`,overflowX:`auto`},children:(0,U.jsxs)(`table`,{style:{width:`100%`,borderCollapse:`collapse`,textAlign:`left`,fontSize:`0.84rem`},children:[(0,U.jsx)(`thead`,{children:(0,U.jsxs)(`tr`,{style:{borderBottom:`1px solid var(--border-subtle)`,color:`#94a3b8`},children:[(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Role Title`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Company`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Status`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Next Action`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Date Due`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Source`}),(0,U.jsx)(`th`,{style:{padding:`0.75rem`},children:`Actions`})]})}),(0,U.jsx)(`tbody`,{children:t.map(e=>(0,U.jsxs)(`tr`,{style:{borderBottom:`1px solid var(--border-subtle)`},children:[(0,U.jsx)(`td`,{style:{padding:`0.75rem`,fontWeight:600,color:`#f8fafc`},children:e.jobTitle}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`,color:`#38bdf8`},children:e.company}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`},children:(0,U.jsx)(`span`,{style:{padding:`0.2rem 0.5rem`,borderRadius:`4px`,background:`rgba(99, 102, 241, 0.15)`,color:`#818cf8`,fontSize:`0.74rem`,fontWeight:700},children:e.status})}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`,color:`#cbd5e1`},children:e.nextAction||`-`}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`,color:`#94a3b8`},children:e.nextActionDate||`-`}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`,color:`#94a3b8`},children:e.source||`Direct`}),(0,U.jsx)(`td`,{style:{padding:`0.75rem`},children:(0,U.jsxs)(`div`,{style:{display:`flex`,gap:`0.5rem`},children:[(0,U.jsx)(`button`,{onClick:()=>A(e),style:{background:`none`,border:`none`,color:`#38bdf8`,cursor:`pointer`},children:(0,U.jsx)(Zt,{size:14})}),(0,U.jsx)(`button`,{onClick:()=>M(e.id),style:{background:`none`,border:`none`,color:`#f43f5e`,cursor:`pointer`},children:(0,U.jsx)(Mn,{size:14})})]})})]},e.id))})]})}),s&&(0,U.jsx)(`div`,{style:{position:`fixed`,inset:0,background:`rgba(0, 0, 0, 0.75)`,backdropFilter:`blur(8px)`,display:`flex`,alignItems:`center`,justifyContent:`center`,padding:`1.5rem`,zIndex:9999},children:(0,U.jsxs)(`div`,{className:`glass-panel`,style:{maxWidth:`550px`,width:`100%`,padding:`2rem`,background:`rgba(15, 23, 42, 0.98)`,border:`1px solid rgba(99, 102, 241, 0.3)`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,marginBottom:`1.25rem`},children:[(0,U.jsx)(`h2`,{style:{fontSize:`1.25rem`,color:`#f8fafc`,fontWeight:700},children:l?`Edit Application Details`:`Track New Job Application`}),(0,U.jsx)(`button`,{onClick:()=>c(!1),style:{background:`none`,border:`none`,color:`#94a3b8`,cursor:`pointer`},children:(0,U.jsx)(Xn,{size:20})})]}),(0,U.jsxs)(`form`,{onSubmit:j,style:{display:`flex`,flexDirection:`column`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Job Title *`}),(0,U.jsx)(`input`,{type:`text`,required:!0,placeholder:`e.g. Full Stack Developer`,value:p,onChange:e=>m(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Company Name *`}),(0,U.jsx)(`input`,{type:`text`,required:!0,placeholder:`e.g. Tata Consultancy Services`,value:d,onChange:e=>f(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`}})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`1fr 1fr`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Pipeline Stage *`}),(0,U.jsx)(`select`,{value:v,onChange:e=>y(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`},children:Dr.map(e=>(0,U.jsx)(`option`,{value:e.id,children:e.label},e.id))})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Source`}),(0,U.jsx)(`input`,{type:`text`,value:E,onChange:e=>D(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`}})]})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`2fr 1fr`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Next Action`}),(0,U.jsx)(`input`,{type:`text`,placeholder:`e.g. Follow up with HR / Prepare for technical interview`,value:S,onChange:e=>C(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Next Action Date`}),(0,U.jsx)(`input`,{type:`date`,value:w,onChange:e=>T(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`}})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.8rem`,color:`#cbd5e1`,marginBottom:`0.3rem`,fontWeight:600},children:`Notes & Interview Learnings`}),(0,U.jsx)(`textarea`,{rows:3,placeholder:`Record interview impressions, test feedback, recruiter contact info...`,value:b,onChange:e=>x(e.target.value),style:{width:`100%`,padding:`0.6rem 0.75rem`,borderRadius:`6px`,background:`rgba(30, 41, 59, 0.6)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.85rem`,fontFamily:`inherit`}})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`flex-end`,gap:`0.75rem`,marginTop:`0.5rem`},children:[(0,U.jsx)(`button`,{type:`button`,onClick:()=>c(!1),className:`btn-secondary`,children:`Cancel`}),(0,U.jsxs)(`button`,{type:`submit`,className:`btn-primary`,children:[(0,U.jsx)(cn,{size:15}),(0,U.jsx)(`span`,{children:`Save Record`})]})]})]})]})})]})};
