// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const CareerJobAlertsView = ({onNavigateTab:e})=>{let[t,n]=(0,_.useState)(!0),[r,i]=(0,_.useState)(!1),[a,o]=(0,_.useState)(``),[s,c]=(0,_.useState)(`full-stack-developer`),[l,u]=(0,_.useState)(`React, JavaScript, Node.js, SQL, Python`),[d,f]=(0,_.useState)(`Pune, Mumbai, Remote`),[p,m]=(0,_.useState)(`Hybrid or Remote`),[h,g]=(0,_.useState)(`Full Time`),[v,y]=(0,_.useState)(`Entry-Level / 0-2 yrs`),[b,x]=(0,_.useState)(`TCS, Tech Mahindra, Infosys, Cognizant, Startups`),[S,C]=(0,_.useState)(`Daily`),[w,T]=(0,_.useState)({new_matching_job:!0,high_priority_job:!0,closing_soon_job:!0,application_reminder:!0,interview_reminder:!0,profile_improvement_reminder:!0}),[E,D]=(0,_.useState)(`default`);(0,_.useEffect)(()=>{O(),typeof window<`u`&&`Notification`in window&&D(Notification.permission)},[]);let O=async()=>{n(!0);try{let e=await W.getNotificationPreferences();e&&T({new_matching_job:e.new_matching_job!==!1,high_priority_job:e.high_priority_job!==!1,closing_soon_job:e.closing_soon_job!==!1,application_reminder:e.application_reminder!==!1,interview_reminder:e.interview_reminder!==!1,profile_improvement_reminder:e.profile_improvement_reminder!==!1})}catch(e){console.warn(e)}finally{n(!1)}};return(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`2rem`,maxWidth:`1000px`,margin:`0 auto`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`2rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{background:`rgba(245, 158, 11, 0.15)`,color:`#f59e0b`,padding:`0.2rem 0.65rem`,borderRadius:`6px`,fontSize:`0.75rem`,fontWeight:700},children:`Module 9 • /jobs/alerts`}),(0,U.jsx)(`span`,{style:{color:`#94a3b8`,fontSize:`0.82rem`},children:`Candidate Subscription Engine`})]}),(0,U.jsx)(`h1`,{style:{fontSize:`1.9rem`,color:`#f8fafc`,fontWeight:800},children:`Live Student Job Alert Preferences`}),(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.92rem`,marginTop:`0.35rem`},children:`Set criteria to receive instant push alerts whenever authorized job boards ingest openings matching your target roles.`})]}),(0,U.jsx)(`button`,{onClick:()=>e(`career_jobs`),className:`btn-secondary`,children:(0,U.jsx)(`span`,{children:`← View Live Jobs`})})]}),(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`,padding:`0.85rem 1rem`,background:`rgba(15, 23, 42, 0.6)`,border:`1px solid rgba(0, 212, 255, 0.3)`,borderRadius:`8px`,display:`flex`,justifyContent:`space-between`,alignItems:`center`,flexWrap:`wrap`,gap:`0.75rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.65rem`,fontSize:`0.84rem`},children:[(0,U.jsx)(ce,{size:18,color:`#00D4FF`}),(0,U.jsxs)(`span`,{style:{color:`#e2e8f0`},children:[(0,U.jsx)(`strong`,{children:`Browser Push Status:`}),` `,E===`granted`?`Active & Subscribed`:`Permission Required for Desktop Alerts`]})]}),E!==`granted`&&(0,U.jsx)(`button`,{onClick:async()=>{let e=await Mr();e.granted?(D(`granted`),alert(`Browser web push notifications successfully enabled!`)):(D(`denied`),e.error&&alert(e.error))},className:`btn-primary`,style:{padding:`0.4rem 1rem`,fontSize:`0.8rem`},children:(0,U.jsx)(`span`,{children:`Enable Browser Push`})})]})]}),a&&(0,U.jsxs)(`div`,{style:{background:`rgba(16, 185, 129, 0.15)`,border:`1px solid rgba(16, 185, 129, 0.4)`,borderRadius:`8px`,padding:`1rem`,color:`#34d399`,display:`flex`,alignItems:`center`,gap:`0.5rem`,fontWeight:600},children:[(0,U.jsx)(H,{size:18}),(0,U.jsx)(`span`,{children:a})]}),(0,U.jsxs)(`form`,{onSubmit:async e=>{e.preventDefault(),i(!0),o(``);try{await W.updateNotificationPreferences(w),o(`Job alert criteria and notification preferences saved successfully!`),setTimeout(()=>o(``),4e3)}catch(e){alert(e.message||`Error saving alert preferences`)}finally{i(!1)}},style:{display:`flex`,flexDirection:`column`,gap:`1.75rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,marginBottom:`1.25rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(ve,{size:18,color:`#00D4FF`}),(0,U.jsx)(`span`,{children:`1. Match Filters & Role Preferences`})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(260px, 1fr))`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Target Job Role`}),(0,U.jsxs)(`select`,{value:s,onChange:e=>c(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`},children:[(0,U.jsx)(`option`,{value:`full-stack-developer`,children:`Full Stack Developer`}),(0,U.jsx)(`option`,{value:`ai-ml-engineer`,children:`AI / Machine Learning Engineer`}),(0,U.jsx)(`option`,{value:`data-analyst`,children:`Data Analyst & BI Specialist`}),(0,U.jsx)(`option`,{value:`cloud-engineer`,children:`Cloud & DevOps Associate`}),(0,U.jsx)(`option`,{value:`cybersecurity-analyst`,children:`Cybersecurity Analyst`})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Job Type`}),(0,U.jsxs)(`select`,{value:h,onChange:e=>g(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`},children:[(0,U.jsx)(`option`,{value:`Full Time`,children:`Full-Time Positions`}),(0,U.jsx)(`option`,{value:`Internship`,children:`Student Internships & Apprenticeships`}),(0,U.jsx)(`option`,{value:`Part Time`,children:`Part-Time / Contract`}),(0,U.jsx)(`option`,{value:`All`,children:`All Job Types`})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Remote Preference`}),(0,U.jsxs)(`select`,{value:p,onChange:e=>m(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`},children:[(0,U.jsx)(`option`,{value:`Hybrid or Remote`,children:`Hybrid or Remote`}),(0,U.jsx)(`option`,{value:`Remote Only`,children:`Remote Only`}),(0,U.jsx)(`option`,{value:`In-Office Only`,children:`In-Office Only`}),(0,U.jsx)(`option`,{value:`Any`,children:`Any Arrangement`})]})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Experience Level`}),(0,U.jsxs)(`select`,{value:v,onChange:e=>y(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`},children:[(0,U.jsx)(`option`,{value:`Entry-Level / 0-2 yrs`,children:`Entry-Level / 0-2 years (Campus / Fresher)`}),(0,U.jsx)(`option`,{value:`Intern`,children:`Intern / Student`}),(0,U.jsx)(`option`,{value:`Mid-Level`,children:`Mid-Level (2-5 years)`})]})]})]}),(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`},children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Primary Matching Skills (comma separated)`}),(0,U.jsx)(`input`,{type:`text`,value:l,onChange:e=>u(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`}})]}),(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`,display:`grid`,gridTemplateColumns:`1fr 1fr`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Preferred Locations`}),(0,U.jsx)(`input`,{type:`text`,value:d,onChange:e=>f(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`}})]}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.35rem`,fontWeight:600},children:`Preferred Companies / Sectors`}),(0,U.jsx)(`input`,{type:`text`,value:b,onChange:e=>x(e.target.value),style:{width:`100%`,padding:`0.65rem 0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.7)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.9rem`}})]})]})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,marginBottom:`1.25rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(ze,{size:18,color:`#a855f7`}),(0,U.jsx)(`span`,{children:`2. Alert Frequency & Notification Types`})]}),(0,U.jsxs)(`div`,{style:{marginBottom:`1.5rem`},children:[(0,U.jsx)(`label`,{style:{display:`block`,fontSize:`0.82rem`,color:`#cbd5e1`,marginBottom:`0.5rem`,fontWeight:600},children:`Dispatch Frequency`}),(0,U.jsx)(`div`,{style:{display:`flex`,gap:`1rem`,flexWrap:`wrap`},children:[`Instant (As Ingested)`,`Daily Digest`,`Weekly Roundup`].map(e=>(0,U.jsxs)(`label`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,cursor:`pointer`,fontSize:`0.85rem`,color:`#e2e8f0`},children:[(0,U.jsx)(`input`,{type:`radio`,name:`freq`,checked:S.toLowerCase().includes(e.split(` `)[0].toLowerCase()),onChange:()=>C(e),style:{accentColor:`#00D4FF`}}),(0,U.jsx)(`span`,{children:e})]},e))})]}),(0,U.jsx)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(280px, 1fr))`,gap:`1rem`},children:[{key:`new_matching_job`,label:`New Matching Jobs (>70% Skill Compatibility)`},{key:`high_priority_job`,label:`High-Priority Government & Corporate Openings`},{key:`closing_soon_job`,label:`Application Deadlines Closing Soon`},{key:`application_reminder`,label:`Follow-up Reminders for Active Applications`},{key:`interview_reminder`,label:`Interview Preparation Reminders`},{key:`profile_improvement_reminder`,label:`Profile Strength Optimization Alerts`}].map(e=>(0,U.jsxs)(`label`,{style:{display:`flex`,alignItems:`center`,gap:`0.65rem`,padding:`0.75rem`,background:`rgba(15, 23, 42, 0.6)`,border:`1px solid var(--border-subtle)`,borderRadius:`8px`,cursor:`pointer`,fontSize:`0.84rem`,color:`#f8fafc`},children:[(0,U.jsx)(`input`,{type:`checkbox`,checked:w[e.key]!==!1,onChange:t=>T({...w,[e.key]:t.target.checked}),style:{width:`16px`,height:`16px`,accentColor:`#6366f1`}}),(0,U.jsx)(`span`,{children:e.label})]},e.key))})]}),(0,U.jsx)(`div`,{style:{display:`flex`,justifyContent:`flex-end`,gap:`1rem`},children:(0,U.jsxs)(`button`,{type:`submit`,disabled:r,className:`btn-primary`,style:{padding:`0.85rem 2.2rem`,fontSize:`0.95rem`},children:[(0,U.jsx)(cn,{size:16}),(0,U.jsx)(`span`,{children:r?`Saving...`:`Save Job Alert Preferences`})]})})]})]})};
