// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const CareerProfileAnalyzerView = ({onNavigateTab:e})=>{let[t,n]=(0,_.useState)(`Aarav Deshmukh
Computer Engineering student at COEP Technological University, Pune (Class of 2027).
Passionate about web development and building software solutions. Skilled in JavaScript, React, HTML, CSS, SQL and Python.
Built a Citizen Service Portal for rural scholarship distribution using React and Node.js.
Interested in full stack engineer opportunities in Pune and remote.`),[r,i]=(0,_.useState)(!1),[a,o]=(0,_.useState)(null),[s,c]=(0,_.useState)(null),l=async e=>{if(e.preventDefault(),t.trim()){i(!0);try{let e=await W.analyzeProfile(t);o(e)}catch(e){alert(e.message||`Error analyzing profile text`)}finally{i(!1)}}},u=(e,t)=>{navigator.clipboard.writeText(e),c(t),setTimeout(()=>c(null),2500)};return(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`2rem`,maxWidth:`1050px`,margin:`0 auto`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`2rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`flex-start`,flexWrap:`wrap`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`,marginBottom:`0.4rem`},children:[(0,U.jsx)(`span`,{style:{background:`rgba(56, 189, 248, 0.15)`,color:`#38bdf8`,padding:`0.2rem 0.65rem`,borderRadius:`6px`,fontSize:`0.75rem`,fontWeight:700},children:`Module 2 • /career/profile-analyzer`}),(0,U.jsx)(`span`,{style:{color:`#94a3b8`,fontSize:`0.82rem`},children:`Audited Guidance`})]}),(0,U.jsx)(`h1`,{style:{fontSize:`1.85rem`,color:`#f8fafc`,fontWeight:800},children:`LinkedIn & Public Profile Guidance`}),(0,U.jsx)(`p`,{style:{color:`#cbd5e1`,fontSize:`0.92rem`,marginTop:`0.35rem`,maxWidth:`750px`},children:`Paste your public profile or resume bio to evaluate its strength, identify missing professional elements, and generate grounded rewrite suggestions.`})]}),(0,U.jsx)(`button`,{type:`button`,onClick:()=>e(`career_profile`),className:`btn-secondary`,children:(0,U.jsx)(`span`,{children:`← Return to Profile Builder`})})]}),(0,U.jsxs)(`div`,{style:{marginTop:`1.25rem`,padding:`0.85rem 1rem`,background:`rgba(15, 23, 42, 0.6)`,border:`1px solid rgba(245, 158, 11, 0.3)`,borderRadius:`8px`,display:`flex`,alignItems:`center`,gap:`0.75rem`,fontSize:`0.82rem`,color:`#fcd34d`},children:[(0,U.jsx)(vn,{size:18,color:`#f59e0b`}),(0,U.jsxs)(`span`,{children:[(0,U.jsx)(`strong`,{children:`Transparency Notice:`}),` SkillBridge never scrapes private LinkedIn profiles or accesses credentials. All guidance is performed on the public text provided by you below and never modifies external accounts.`]})]})]}),(0,U.jsx)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:(0,U.jsxs)(`form`,{onSubmit:l,style:{display:`flex`,flexDirection:`column`,gap:`1rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`},children:[(0,U.jsxs)(`label`,{style:{fontSize:`0.92rem`,color:`#f8fafc`,fontWeight:600,display:`flex`,alignItems:`center`,gap:`0.4rem`},children:[(0,U.jsx)(rt,{size:17,color:`#38bdf8`}),(0,U.jsx)(`span`,{children:`Paste Your Public Profile or Bio Text`})]}),(0,U.jsxs)(`span`,{style:{fontSize:`0.78rem`,color:`#94a3b8`},children:[`Character count: `,t.length]})]}),(0,U.jsx)(`textarea`,{rows:6,value:t,onChange:e=>n(e.target.value),placeholder:`Paste your headline, about summary, skills, and projects here...`,style:{width:`100%`,padding:`0.85rem`,borderRadius:`8px`,background:`rgba(15, 23, 42, 0.8)`,border:`1px solid var(--border-subtle)`,color:`#f8fafc`,fontSize:`0.88rem`,fontFamily:`inherit`,lineHeight:`1.5`}}),(0,U.jsx)(`div`,{style:{display:`flex`,justifyContent:`flex-end`,gap:`1rem`},children:(0,U.jsxs)(`button`,{type:`submit`,disabled:r||!t.trim(),className:`btn-primary`,style:{padding:`0.75rem 1.75rem`,fontSize:`0.92rem`},children:[(0,U.jsx)(wn,{size:17}),(0,U.jsx)(`span`,{children:r?`Analyzing Profile Sections...`:`Analyze Profile Strength`})]})})]})}),a&&(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`1.75rem`},children:[(0,U.jsx)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,flexWrap:`wrap`,gap:`1.5rem`},children:[(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`span`,{style:{fontSize:`0.82rem`,textTransform:`uppercase`,letterSpacing:`0.06em`,color:`#94a3b8`,fontWeight:700},children:`Profile Strength Audit`}),(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`baseline`,gap:`0.75rem`,marginTop:`0.25rem`},children:[(0,U.jsxs)(`h2`,{style:{fontSize:`2.5rem`,fontWeight:900,color:a.profile_strength>=75?`#34d399`:`#fbbf24`},children:[a.profile_strength,`%`]}),(0,U.jsx)(`span`,{style:{fontSize:`0.95rem`,color:`#cbd5e1`},children:a.profile_strength>=75?`Strong Profile`:`Needs Optimization`})]})]}),(0,U.jsxs)(`div`,{style:{flex:`1 1 300px`,maxWidth:`500px`},children:[(0,U.jsx)(`div`,{style:{height:`10px`,background:`rgba(255, 255, 255, 0.1)`,borderRadius:`9999px`,overflow:`hidden`},children:(0,U.jsx)(`div`,{style:{width:`${a.profile_strength}%`,height:`100%`,background:a.profile_strength>=75?`linear-gradient(90deg, #10b981, #06b6d4)`:`linear-gradient(90deg, #f59e0b, #6366f1)`,transition:`width 0.6s ease`}})}),(0,U.jsx)(`div`,{style:{fontSize:`0.76rem`,color:`#94a3b8`,marginTop:`0.4rem`,textAlign:`right`},children:`Weighted by recruiter search heuristics & ATS scan patterns`})]})]})}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(360px, 1fr))`,gap:`1.5rem`},children:[(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.5rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.1rem`,color:`#f8fafc`,marginBottom:`1rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(H,{size:18,color:`#10b981`}),(0,U.jsx)(`span`,{children:`Completeness Checklist`})]}),(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.65rem`},children:a.completeness_checklist?.map((e,t)=>(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,justifyContent:`space-between`,padding:`0.6rem 0.75rem`,borderRadius:`8px`,background:e.completed?`rgba(16, 185, 129, 0.08)`:`rgba(244, 63, 94, 0.08)`,border:`1px solid ${e.completed?`rgba(16, 185, 129, 0.2)`:`rgba(244, 63, 94, 0.2)`}`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.6rem`,fontSize:`0.84rem`},children:[e.completed?(0,U.jsx)(H,{size:16,color:`#34d399`}):(0,U.jsx)(Fe,{size:16,color:`#f43f5e`}),(0,U.jsx)(`span`,{style:{color:e.completed?`#f8fafc`:`#fda4af`},children:e.item})]}),(0,U.jsxs)(`span`,{style:{fontSize:`0.74rem`,color:`#94a3b8`,fontWeight:600},children:[`+`,e.weight,`%`]})]},t))})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.5rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.1rem`,color:`#f8fafc`,marginBottom:`1rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(Pn,{size:18,color:`#38bdf8`}),(0,U.jsx)(`span`,{children:`Actionable Improvement Suggestions`})]}),(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:a.improvement_suggestions?.map((e,t)=>(0,U.jsx)(`div`,{style:{padding:`0.75rem`,background:`rgba(15, 23, 42, 0.6)`,borderLeft:`3px solid #38bdf8`,borderRadius:`0 8px 8px 0`,fontSize:`0.84rem`,color:`#e2e8f0`,lineHeight:`1.5`},children:e},t))})]})]}),(0,U.jsxs)(`div`,{className:`glass-panel`,style:{padding:`1.75rem`},children:[(0,U.jsxs)(`h3`,{style:{fontSize:`1.2rem`,color:`#f8fafc`,marginBottom:`1.25rem`,display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(wn,{size:18,color:`#a855f7`}),(0,U.jsx)(`span`,{children:`Recommended Profile Content Rewrites`})]}),(0,U.jsxs)(`div`,{style:{display:`grid`,gridTemplateColumns:`repeat(auto-fit, minmax(320px, 1fr))`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.6)`,border:`1px solid var(--border-subtle)`,borderRadius:`10px`,padding:`1rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,marginBottom:`0.5rem`},children:[(0,U.jsx)(`span`,{style:{fontSize:`0.76rem`,textTransform:`uppercase`,color:`#38bdf8`,fontWeight:700},children:`Suggested Headline`}),(0,U.jsxs)(`button`,{onClick:()=>u(a.suggested_headline,`headline`),style:{background:`none`,border:`none`,color:s===`headline`?`#34d399`:`#94a3b8`,cursor:`pointer`,display:`flex`,alignItems:`center`,gap:`0.25rem`,fontSize:`0.76rem`},children:[s===`headline`?(0,U.jsx)(we,{size:13}):(0,U.jsx)(Ge,{size:13}),(0,U.jsx)(`span`,{children:s===`headline`?`Copied`:`Copy`})]})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.88rem`,color:`#f8fafc`,fontWeight:500,lineHeight:`1.4`},children:a.suggested_headline})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.6)`,border:`1px solid var(--border-subtle)`,borderRadius:`10px`,padding:`1rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,marginBottom:`0.5rem`},children:[(0,U.jsx)(`span`,{style:{fontSize:`0.76rem`,textTransform:`uppercase`,color:`#a855f7`,fontWeight:700},children:`Suggested About / Summary`}),(0,U.jsxs)(`button`,{onClick:()=>u(a.suggested_about_section,`about`),style:{background:`none`,border:`none`,color:s===`about`?`#34d399`:`#94a3b8`,cursor:`pointer`,display:`flex`,alignItems:`center`,gap:`0.25rem`,fontSize:`0.76rem`},children:[s===`about`?(0,U.jsx)(we,{size:13}):(0,U.jsx)(Ge,{size:13}),(0,U.jsx)(`span`,{children:s===`about`?`Copied`:`Copy`})]})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.84rem`,color:`#cbd5e1`,lineHeight:`1.5`},children:a.suggested_about_section})]}),(0,U.jsxs)(`div`,{style:{background:`rgba(15, 23, 42, 0.6)`,border:`1px solid var(--border-subtle)`,borderRadius:`10px`,padding:`1rem`,gridColumn:`1 / -1`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`,marginBottom:`0.5rem`},children:[(0,U.jsx)(`span`,{style:{fontSize:`0.76rem`,textTransform:`uppercase`,color:`#10b981`,fontWeight:700},children:`Suggested Quantified Project Bullet`}),(0,U.jsxs)(`button`,{onClick:()=>u(a.suggested_project_description,`project`),style:{background:`none`,border:`none`,color:s===`project`?`#34d399`:`#94a3b8`,cursor:`pointer`,display:`flex`,alignItems:`center`,gap:`0.25rem`,fontSize:`0.76rem`},children:[s===`project`?(0,U.jsx)(we,{size:13}):(0,U.jsx)(Ge,{size:13}),(0,U.jsx)(`span`,{children:s===`project`?`Copied`:`Copy`})]})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.84rem`,color:`#cbd5e1`,lineHeight:`1.5`},children:a.suggested_project_description})]})]})]})]})]})};
