// @ts-nocheck
import React, { useState, useEffect, useRef } from "react";
import { jsx, jsxs, Fragment } from "react/jsx-runtime";
import { api as W } from "../lib/api";
import { authService as ap, defaultStudent as rp } from "../lib/auth";
import {
  Activity as P,
  ArrowLeft as ee,
  ArrowRight as ne,
  ArrowUpRight as ie,
  Award as oe,
  Bell as ce,
  Binary as ue,
  BookOpen as fe,
  BookmarkCheck as me,
  Bookmark as L,
  Bot as ge,
  Briefcase as ve,
  Building as R,
  Building2 as xe,
  BarChart3 as z,
  CheckCheck as B,
  Check as we,
  ChevronDown as Ee,
  ChevronRight as Oe,
  AlertCircle as Ae,
  CheckCircle as H,
  HelpCircle as Ne,
  XCircle as Fe,
  ClipboardCheck as Le,
  Clock as ze,
  Code as Ve,
  Compass as Ue,
  Copy as Ge,
  Database as qe,
  Download as Ye,
  MoreVertical as Ze,
  ExternalLink as $e,
  FileCheck as tt,
  FileText as rt,
  Flame as at,
  FolderGit2 as st,
  Filter as lt,
  GitCompare as dt,
  Globe as pt,
  GraduationCap as ht,
  Home as _t,
  Info as yt,
  Kanban as xt,
  Layers as Ct,
  LayoutDashboard as Tt,
  Lightbulb as Dt,
  Link2 as kt,
  Lock as jt,
  LogIn as Nt,
  LogOut as Ft,
  Mail as Lt,
  MapPin as zt,
  MessageSquare as Vt,
  MicOff as Ut,
  Mic as Gt,
  Milestone as qt,
  AlertOctagon as Yt,
  Pen as Zt,
  Phone as $t,
  Plus as tn,
  Printer as rn,
  RefreshCw as on,
  Save as cn,
  Scale as un,
  Search as fn,
  Send as mn,
  Server as gn,
  ShieldAlert as vn,
  ShieldCheck as bn,
  Shield as Sn,
  Sparkles as wn,
  Star as En,
  Table as On,
  Target as An,
  Trash2 as Mn,
  TrendingUp as Pn,
  TriangleAlert as In,
  Trophy as Rn,
  Upload as Bn,
  UserCheck as Hn,
  User as Wn,
  Users as Kn,
  Video as Jn,
  X as Xn,
  Zap as Qn
} from "lucide-react";

const _ = { useState, useEffect, useRef };
const U = { jsx, jsxs, Fragment };

export const NotificationModal = ({isOpen:e,onClose:t,onNavigateTab:n})=>{let[r,i]=(0,_.useState)(`notifications`),[a,o]=(0,_.useState)([]),[s,c]=(0,_.useState)({enabled:!0,new_matching_job:!0,high_priority_job:!0,closing_soon_job:!0,application_reminder:!0,interview_reminder:!0,profile_improvement_reminder:!0}),[l,u]=(0,_.useState)(`default`),[d,f]=(0,_.useState)(!1),[p,m]=(0,_.useState)(!1);(0,_.useEffect)(()=>{e&&(h(),typeof window<`u`&&`Notification`in window&&u(Notification.permission))},[e]);let h=async()=>{try{let[e,t]=await Promise.all([W.getNotifications(),W.getNotificationPreferences()]);o(e||[]),t&&c(t)}catch(e){console.error(e)}},g=async()=>{let e=await Mr();e.granted?(u(`granted`),alert(`Browser web push notifications successfully enabled!`)):(u(`denied`),e.error&&alert(e.error))},v=async e=>{e.preventDefault(),f(!0);try{await W.updateNotificationPreferences(s),m(!0),setTimeout(()=>m(!1),3e3)}catch(e){alert(e.message||`Error updating preferences`)}finally{f(!1)}},y=e=>{t(),e.link===`/jobs`||e.link===`career_jobs`?n(`career_jobs`):e.link===`/applications`||e.link===`career_applications`?n(`career_applications`):e.link===`/career/profile-analyzer`||e.link===`career_profile_analyzer`?n(`career_profile_analyzer`):n(`career_dashboard`)};return e?(0,U.jsx)(`div`,{style:{position:`fixed`,inset:0,background:`rgba(0, 0, 0, 0.75)`,backdropFilter:`blur(8px)`,display:`flex`,alignItems:`center`,justifyContent:`center`,padding:`1.5rem`,zIndex:99999},children:(0,U.jsxs)(`div`,{className:`glass-panel`,style:{maxWidth:`560px`,width:`100%`,maxHeight:`85vh`,display:`flex`,flexDirection:`column`,background:`rgba(15, 23, 42, 0.98)`,border:`1px solid rgba(99, 102, 241, 0.3)`,boxShadow:`0 20px 40px rgba(0, 0, 0, 0.7)`,overflow:`hidden`},children:[(0,U.jsxs)(`div`,{style:{padding:`1.25rem 1.5rem`,borderBottom:`1px solid var(--border-subtle)`,display:`flex`,justifyContent:`space-between`,alignItems:`center`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.65rem`},children:[(0,U.jsx)(`div`,{style:{background:`rgba(245, 158, 11, 0.15)`,color:`#f59e0b`,padding:`0.4rem`,borderRadius:`8px`},children:(0,U.jsx)(ce,{size:18})}),(0,U.jsxs)(`div`,{children:[(0,U.jsx)(`h2`,{style:{fontSize:`1.15rem`,color:`#f8fafc`,fontWeight:700},children:`Career Notifications & Alerts`}),(0,U.jsx)(`div`,{style:{fontSize:`0.74rem`,color:`#94a3b8`},children:`Live Job Updates & Application Reminders`})]})]}),(0,U.jsx)(`button`,{onClick:t,style:{background:`none`,border:`none`,color:`#94a3b8`,cursor:`pointer`},children:(0,U.jsx)(Xn,{size:20})})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,borderBottom:`1px solid var(--border-subtle)`,background:`rgba(15, 23, 42, 0.5)`},children:[(0,U.jsxs)(`button`,{onClick:()=>i(`notifications`),style:{flex:1,padding:`0.75rem`,background:`none`,border:`none`,borderBottom:r===`notifications`?`2px solid #38bdf8`:`2px solid transparent`,color:r===`notifications`?`#38bdf8`:`#94a3b8`,fontSize:`0.84rem`,fontWeight:600,cursor:`pointer`},children:[`Alerts History (`,a.length,`)`]}),(0,U.jsx)(`button`,{onClick:()=>i(`preferences`),style:{flex:1,padding:`0.75rem`,background:`none`,border:`none`,borderBottom:r===`preferences`?`2px solid #38bdf8`:`2px solid transparent`,color:r===`preferences`?`#38bdf8`:`#94a3b8`,fontSize:`0.84rem`,fontWeight:600,cursor:`pointer`},children:`Alert Preferences & Web Push`})]}),(0,U.jsx)(`div`,{style:{padding:`1.5rem`,overflowY:`auto`,flex:1,display:`flex`,flexDirection:`column`,gap:`1rem`},children:r===`notifications`?(0,U.jsx)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:a.length===0?(0,U.jsx)(`div`,{style:{textAlign:`center`,padding:`2rem`,color:`#64748b`},children:`No new career notifications.`}):a.map(e=>(0,U.jsxs)(`div`,{onClick:()=>y(e),className:`glass-card`,style:{cursor:`pointer`,padding:`0.85rem`,display:`flex`,flexDirection:`column`,gap:`0.35rem`,borderLeft:e.type===`new_job`?`3px solid #38bdf8`:`3px solid #f59e0b`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,justifyContent:`space-between`,alignItems:`center`},children:[(0,U.jsx)(`span`,{style:{fontSize:`0.85rem`,fontWeight:600,color:`#f8fafc`},children:e.title}),!e.read&&(0,U.jsx)(`span`,{style:{width:`7px`,height:`7px`,borderRadius:`50%`,background:`#38bdf8`}})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.78rem`,color:`#cbd5e1`,lineHeight:`1.4`},children:e.message}),(0,U.jsx)(`div`,{style:{fontSize:`0.7rem`,color:`#64748b`,marginTop:`0.2rem`},children:`Click to inspect opening →`})]},e.id))}):(0,U.jsxs)(`form`,{onSubmit:v,style:{display:`flex`,flexDirection:`column`,gap:`1.25rem`},children:[(0,U.jsxs)(`div`,{style:{background:`rgba(30, 41, 59, 0.6)`,padding:`1rem`,borderRadius:`8px`,border:`1px solid var(--border-subtle)`,display:`flex`,flexDirection:`column`,gap:`0.5rem`},children:[(0,U.jsxs)(`div`,{style:{display:`flex`,alignItems:`center`,gap:`0.5rem`},children:[(0,U.jsx)(bn,{size:16,color:`#10b981`}),(0,U.jsx)(`span`,{style:{fontSize:`0.85rem`,fontWeight:600,color:`#f8fafc`},children:`Browser Push Notifications`})]}),(0,U.jsx)(`p`,{style:{fontSize:`0.78rem`,color:`#94a3b8`,lineHeight:`1.4`},children:`Enable desktop alerts so you never miss high-compatibility job postings from verified public feeds or urgent application deadlines.`}),(0,U.jsx)(`div`,{style:{marginTop:`0.25rem`},children:l===`granted`?(0,U.jsxs)(`div`,{style:{color:`#34d399`,fontSize:`0.78rem`,display:`flex`,alignItems:`center`,gap:`0.35rem`,fontWeight:600},children:[(0,U.jsx)(H,{size:14}),(0,U.jsx)(`span`,{children:`Web Push Alerts Active on this device`})]}):(0,U.jsxs)(`button`,{type:`button`,onClick:g,className:`btn-primary`,style:{padding:`0.45rem 1rem`,fontSize:`0.8rem`},children:[(0,U.jsx)(ce,{size:13}),(0,U.jsx)(`span`,{children:`Enable Browser Notifications`})]})})]}),(0,U.jsxs)(`div`,{style:{display:`flex`,flexDirection:`column`,gap:`0.75rem`},children:[(0,U.jsx)(`div`,{style:{fontSize:`0.8rem`,fontWeight:700,color:`#cbd5e1`,textTransform:`uppercase`,letterSpacing:`0.05em`},children:`Choose What You Want to Be Alerted For`}),[{key:`new_matching_job`,label:`New Matching Jobs (>70% skill fit)`},{key:`high_priority_job`,label:`High-Priority Enterprise Positions`},{key:`closing_soon_job`,label:`Openings Closing Soon`},{key:`application_reminder`,label:`Application Follow-up Reminders`},{key:`interview_reminder`,label:`Scheduled Interview Alerts`},{key:`profile_improvement_reminder`,label:`Profile Strength Improvement Tips`}].map(e=>(0,U.jsxs)(`label`,{style:{display:`flex`,alignItems:`center`,gap:`0.65rem`,cursor:`pointer`,fontSize:`0.84rem`,color:`#e2e8f0`},children:[(0,U.jsx)(`input`,{type:`checkbox`,checked:s[e.key]!==!1,onChange:t=>c({...s,[e.key]:t.target.checked}),style:{width:`16px`,height:`16px`,accentColor:`#6366f1`}}),(0,U.jsx)(`span`,{children:e.label})]},e.key))]}),p&&(0,U.jsx)(`div`,{style:{color:`#34d399`,fontSize:`0.8rem`,fontWeight:600},children:`Preferences saved successfully!`}),(0,U.jsx)(`div`,{style:{display:`flex`,justifyContent:`flex-end`,paddingTop:`0.75rem`,borderTop:`1px solid var(--border-subtle)`},children:(0,U.jsxs)(`button`,{type:`submit`,disabled:d,className:`btn-primary`,style:{padding:`0.55rem 1.25rem`,fontSize:`0.84rem`},children:[(0,U.jsx)(cn,{size:14}),(0,U.jsx)(`span`,{children:d?`Saving...`:`Save Preferences`})]})})]})})]})}):null};
